

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: The Least Astonished

# Short bio or description (displayed in the header)
description: Hi! I am Akinwale Alexander ðŸ¤“ . A software engineer, an expert using languages such as Scala, Kafka, Akka-stream, ZIO , etc, for the greater good of humanity. I'm a contributor on various open source projects. A technology advocate for Scala in Africa, and I stand to push the envelope of software development as far as I can through dilligence, collaboration and helping others . All views expressed here are mine and doesn't in any way represent my the stance of my company.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/2574957?s=400&u=12bb8593d157fba19756289afed6f72ed2b829bf&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: yeleywale@gmail.com
  facebook:
  flickr:
  github: yeleywale
  instagram:
  linkedin: https://linkedin.com/in/yeleywale
  pinterest:
  rss: akinwale
  twitter: yeleywale
  stackoverflow:  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: timale

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

url: https://www.alexakinwale.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/


# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed # You might prefer to minify using :compressed
  
# Use the following plug-ins
# gems:

plugins:
  - jemoji


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

encoding: utf-8

# show_drafts: true


